[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
[[module.mounts]]
    source = "dist/slideshow-gallery.js"
    target = "assets/js/modules/slideshow-gallery/slideshow-gallery.js"
  [[module.mounts]]
    source = "dist"
    target = "assets/scss"
    includeFiles = "slideshow-gallery.scss"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'i18n'
    target = 'i18n'
  [[module.mounts]]
    source = 'data'
    target = 'data' 
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"  
    
