resourcedir = '../resources/'
baseURL = 'http://example.org/'
languageCode = "en-us"
defaultContentLanguage = "en"
title = 'Test site for mod-image-lightbox-gallery'

timeout = "180s"

[module]
  replacements = 'github.com/d-oit/mod-image-lightbox-gallery -> ../..'
  # Build and serve using local mod-template clone declared in the named Hugo workspace:
  workspace = "mod-image-lightbox-gallery.work"
  [[module.imports]]
    path = "github.com/d-oit/mod-image-lightbox-gallery"
  [[module.imports]]
    path = "github.com/gethinode/hinode"
  [[module.imports]]
    path = "github.com/gethinode/mod-bootstrap"
  [[module.imports]]
    path = "github.com/gethinode/mod-csp"
  [[module.imports]]
    path = "github.com/gethinode/mod-flexsearch/v2"
  [[module.imports]]
    path = "github.com/gethinode/mod-fontawesome"
  [[module.imports]]
    path = "github.com/gethinode/mod-google-analytics"
  [[module.imports]]
    path = "github.com/gethinode/mod-katex"
  [[module.imports]]
    path = "github.com/gethinode/mod-leaflet"
  [[module.imports]]
    path = "github.com/gethinode/mod-lottie"
  [[module.imports]]
    path = "github.com/gethinode/mod-simple-datatables"
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"

 